### ISSUE TITLE
App becomes unusable after using other apps and returning to CameraRoll

### ISSUE THREAD

**Issue by jahirfiquitiva** [kollerlukas/Camera-Roll-Android-App#57]
Pretty much it.

This is what it shows after one returns to the app, but one can't go back to the albums view, or anything, nothing is functional there.

The only 'fix' is to close the app and re-open it.

![screenshot_20170710-184932](https://user-images.githubusercontent.com/10360816/28538176-e9f15b3e-7072-11e7-8708-bd97fbc16e6e.png)

**Comment by kollerlukas** [comment]
Does this happen every time you resume the app?
Does this only happen when you are viewing a picture or when you are just looking at an album?
Does this only happen with pictures, or also with gifs and videos?

**Comment by Narrat** [comment]
Similar error when I had opened a specific folder and used a file manager to move pictures from that folder to another one. 
Camera Roll still has the filenames and shows this green placeholder. 
Looking at one of those "works" but any interaction like displaying information crashes the app. 
Even after a closing the app and a new startup it still insists those recently moved files are there. 

Whereas camera roll did recognize the changes made to a folder where files got deleted by a different program. 
Although in that case camera roll wasn't showing the content of that folder.

Maybe of note. The folder with the problem is located on the external card.

**Comment by kollerlukas** [comment]
@Narrat My guess is that the FileManager doesn't trigger a MediaStore.scanPaths().
Deleting them again in Camera Roll will trigger a scanPaths().
The crash when opening opening the info for one of these photos should be fixed in the next update.

**Comment by kollerlukas** [comment]
@jahirfiquitiva Are you running an Android Verison lower than 5.1?

**Comment by jahirfiquitiva** [comment]
@kollerlukas  Nope. Using Android 7.1.2

**Comment by kollerlukas** [comment]
Found the issue: the album-data is not reloaded correctly, when removed form the memory.

**Comment by kollerlukas** [comment]
Should be fixed now

**Comment by gedling** [comment]
Still happening for me, I'm afraid. Returning to app gives a blank gallery until I refresh. S8+ on 7.0

**Comment by kollerlukas** [comment]
@gedling Are you modifying any files in an other app?

**Comment by gedling** [comment]
I am using a file manager and VLC to delete and move on occasion, yes.
